<a href="https://colab.research.google.com/github/kk12102006/DAV/blob/main/LAB%20PROGRAM%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
dict={
    "name":["A","B","C","D","E","F","G","H","I"],
    "age":[10,None,12,12,None,15,16,19,20],
    "mark":[67,59,80,None,40,45,50,70,60],
    "branch":["cse",None,"ece","ece","mec","eee",None,"cse",None]
}

In [7]:
import pandas as pd

In [40]:
df=pd.DataFrame(dict)
df

  name   age  mark branch
0    A  10.0  67.0    cse
1    B   NaN  59.0   None
2    C  12.0  80.0    ece
3    D  12.0   NaN    ece
4    E   NaN  40.0    mec
5    F  15.0  45.0    eee
6    G  16.0  50.0   None
7    H  19.0  70.0    cse
8    I  20.0  60.0   None

In [27]:
age_median=df["age"].median()
print("Median:",age_median)

Median: 15.0

In [29]:
mark_mean=df["mark"].mean()
print("Mean:",mark_mean)

Mean: 58.875

In [41]:
df["age"]=df["age"].fillna(age_median)
df

  name   age  mark branch
0    A  10.0  67.0    cse
1    B  15.0  59.0   None
2    C  12.0  80.0    ece
3    D  12.0   NaN    ece
4    E  15.0  40.0    mec
5    F  15.0  45.0    eee
6    G  16.0  50.0   None
7    H  19.0  70.0    cse
8    I  20.0  60.0   None

In [42]:
df["mark"]=df["mark"].fillna(mark_mean)
df

  name   age    mark branch
0    A  10.0  67.000    cse
1    B  15.0  59.000   None
2    C  12.0  80.000    ece
3    D  12.0  58.875    ece
4    E  15.0  40.000    mec
5    F  15.0  45.000    eee
6    G  16.0  50.000   None
7    H  19.0  70.000    cse
8    I  20.0  60.000   None

In [43]:
df.isnull().sum()

name      0
age       0
mark      0
branch    3
dtype: int64

In [45]:
df["branch"]=df["branch"].ffill()
df

  name   age    mark branch
0    A  10.0  67.000    cse
1    B  15.0  59.000    cse
2    C  12.0  80.000    ece
3    D  12.0  58.875    ece
4    E  15.0  40.000    mec
5    F  15.0  45.000    eee
6    G  16.0  50.000    eee
7    H  19.0  70.000    cse
8    I  20.0  60.000    cse

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
dict2={
    "Name":["anu","reema","sanjay","ram"],
    "branch":["cse","eee","sce","ece"]
}

In [54]:
df1=pd.DataFrame(dict2)
df1

     Name branch
0     anu    cse
1   reema    eee
2  sanjay    sce
3     ram    ece

In [56]:

encoder=LabelEncoder()