<a href="https://colab.research.google.com/github/kk12102006/DAV/blob/main/LAB%20PROGRAM%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Dataset of Diabetes .csv to Dataset of Diabetes .csv

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("Dataset of Diabetes .csv")

In [5]:
df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [6]:
df.tail()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
995,200,454317,M,71,11.0,97,7.0,7.5,1.7,1.2,1.8,0.6,30.0,Y
996,671,876534,M,31,3.0,60,12.3,4.1,2.2,0.7,2.4,15.4,37.2,Y
997,669,87654,M,30,7.1,81,6.7,4.1,1.1,1.2,2.4,8.1,27.4,Y
998,99,24004,M,38,5.8,59,6.7,5.3,2.0,1.6,2.9,14.0,40.5,Y
999,248,24054,M,54,5.0,67,6.9,3.8,1.7,1.1,3.0,0.7,33.0,Y

In [7]:
df.shape

(1000, 14)

In [8]:
df.columns

Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI', 'CLASS'],
      dtype='object')

In [11]:
df.dtypes

ID             int64
No_Pation      int64
Gender        object
AGE            int64
Urea         float64
Cr             int64
HbA1c        float64
Chol         float64
TG           float64
HDL          float64
LDL          float64
VLDL         float64
BMI          float64
CLASS         object
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB

In [14]:
df.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

In [16]:
df.mean(numeric_only=True)

ID              340.500000
No_Pation    270551.408000
AGE              53.528000
Urea              5.124743
Cr               68.943000
HbA1c             8.281160
Chol              4.862820
TG                2.349610
HDL               1.204750
LDL               2.609790
VLDL              1.854700
BMI              29.578020
dtype: float64

In [18]:
df.median(numeric_only=True)

ID             300.5
No_Pation    34395.5
AGE             55.0
Urea             4.6
Cr              60.0
HbA1c            8.0
Chol             4.8
TG               2.0
HDL              1.1
LDL              2.5
VLDL             0.9
BMI             30.0
dtype: float64

In [19]:
df.min(numeric_only=True)

ID             1.0
No_Pation    123.0
AGE           20.0
Urea           0.5
Cr             6.0
HbA1c          0.9
Chol           0.0
TG             0.3
HDL            0.2
LDL            0.3
VLDL           0.1
BMI           19.0
dtype: float64

In [20]:
df.max(numeric_only=True)

ID                800.00
No_Pation    75435657.00
AGE                79.00
Urea               38.90
Cr                800.00
HbA1c              16.00
Chol               10.30
TG                 13.80
HDL                 9.90
LDL                 9.90
VLDL               35.00
BMI                47.75
dtype: float64

In [21]:
df.var(numeric_only=True)

ID           5.779104e+04
No_Pation    1.142952e+13
AGE          7.742664e+01
Urea         8.615196e+00
Cr           3.598170e+03
HbA1c        6.421172e+00
Chol         1.694521e+00
TG           1.963294e+00
HDL          4.361461e-01
LDL          1.243452e+00
VLDL         1.342196e+01
BMI          2.462530e+01
dtype: float64

In [23]:
df.mode(numeric_only=True)

      ID  No_Pation   AGE  Urea    Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI
0      1   454316.0  55.0   4.3  56.0    8.0   4.4  2.1  1.1  2.5   0.9  30.0
1      2        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
2      3        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
3      4        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
4      5        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
..   ...        ...   ...   ...   ...    ...   ...  ...  ...  ...   ...   ...
195  196        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
196  197        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
197  198        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
198  199        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN
199  200        NaN   NaN   NaN   NaN    NaN   NaN  NaN  NaN  NaN   NaN   NaN

[200 rows x 12 columns]

In [24]:
df.mode()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,1,454316.0,M,55.0,4.3,56.0,8.0,4.4,2.1,1.1,2.5,0.9,30.0,Y
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.count()

ID           1000
No_Pation    1000
Gender       1000
AGE          1000
Urea         1000
Cr           1000
HbA1c        1000
Chol         1000
TG           1000
HDL          1000
LDL          1000
VLDL         1000
BMI          1000
CLASS        1000
dtype: int64

In [27]:
df["Gender"].unique()

array(['F', 'M', 'f'], dtype=object)

In [29]:
df["CLASS"].unique()

array(['N', 'N ', 'P', 'Y', 'Y '], dtype=object)

In [30]:
df.nunique()

ID           800
No_Pation    961
Gender         3
AGE           50
Urea         110
Cr           113
HbA1c        111
Chol          77
TG            69
HDL           48
LDL           65
VLDL          60
BMI           64
CLASS          5
dtype: int64

In [31]:
df.isnull()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [32]:
df.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [33]:
df["Gender"].value_counts()

Gender
M    565
F    434
f      1
Name: count, dtype: int64

In [34]:
df["Gender"].nunique()

3

In [35]:
df_dropna=df.dropna()
df_dropna

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,200,454317,M,71,11.0,97,7.0,7.5,1.7,1.2,1.8,0.6,30.0,Y
996,671,876534,M,31,3.0,60,12.3,4.1,2.2,0.7,2.4,15.4,37.2,Y
997,669,87654,M,30,7.1,81,6.7,4.1,1.1,1.2,2.4,8.1,27.4,Y
998,99,24004,M,38,5.8,59,6.7,5.3,2.0,1.6,2.9,14.0,40.5,Y
999,248,24054,M,54,5.0,67,6.9,3.8,1.7,1.1,3.0,0.7,33.0,Y

In [36]:
df.shape
df_dropna.shape

(1000, 14)

In [37]:
df_dropna.fillna(0)

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,200,454317,M,71,11.0,97,7.0,7.5,1.7,1.2,1.8,0.6,30.0,Y
996,671,876534,M,31,3.0,60,12.3,4.1,2.2,0.7,2.4,15.4,37.2,Y
997,669,87654,M,30,7.1,81,6.7,4.1,1.1,1.2,2.4,8.1,27.4,Y
998,99,24004,M,38,5.8,59,6.7,5.3,2.0,1.6,2.9,14.0,40.5,Y
999,248,24054,M,54,5.0,67,6.9,3.8,1.7,1.1,3.0,0.7,33.0,Y

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [42]:
df[["Gender","AGE"]]

    Gender  AGE
0        F   50
1        M   26
2        F   50
3        F   50
4        M   33
..     ...  ...
995      M   71
996      M   31
997      M   30
998      M   38
999      M   54

[1000 rows x 2 columns]

In [43]:
df[df["AGE"]>75]

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
93,165,45412,F,77,5.0,106,5.4,3.9,2.1,1.2,4.2,1.1,24.0,N
99,186,454316,M,77,5.0,106,5.4,0.0,2.8,0.8,1.8,0.7,19.0,N
382,339,5980,M,77,6.2,99,7.2,3.2,1.1,0.8,2.0,0.5,29.0,Y
384,389,24101,M,77,6.2,99,7.2,3.2,1.1,0.8,2.0,0.5,29.0,Y
617,171,42329,F,79,5.2,54,9.2,6.4,3.0,1.1,4.1,1.3,30.0,Y
632,121,48925,M,76,5.9,56,10.9,4.6,7.0,0.6,1.3,3.1,33.0,Y
635,532,3592,M,76,5.9,56,10.9,4.6,7.0,0.6,1.3,3.1,31.0,Y
877,37,12154,M,76,4.1,52,7.0,3.3,1.6,1.2,1.4,0.7,31.0,Y
909,75,2435,F,76,2.4,41,11.3,5.3,1.7,1.0,3.5,0.8,29.0,Y

In [44]:
df[df["AGE"]>75].count()

ID           9
No_Pation    9
Gender       9
AGE          9
Urea         9
Cr           9
HbA1c        9
Chol         9
TG           9
HDL          9
LDL          9
VLDL         9
BMI          9
CLASS        9
dtype: int64

In [45]:
df.rename(columns={"Age":"AGE(in years)"})

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,200,454317,M,71,11.0,97,7.0,7.5,1.7,1.2,1.8,0.6,30.0,Y
996,671,876534,M,31,3.0,60,12.3,4.1,2.2,0.7,2.4,15.4,37.2,Y
997,669,87654,M,30,7.1,81,6.7,4.1,1.1,1.2,2.4,8.1,27.4,Y
998,99,24004,M,38,5.8,59,6.7,5.3,2.0,1.6,2.9,14.0,40.5,Y
999,248,24054,M,54,5.0,67,6.9,3.8,1.7,1.1,3.0,0.7,33.0,Y

In [48]:
df.rename(columns={"AGE":"AGE_Years"})

,ID,No_Pation,Gender,AGE_Years,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,200,454317,M,71,11.0,97,7.0,7.5,1.7,1.2,1.8,0.6,30.0,Y
996,671,876534,M,31,3.0,60,12.3,4.1,2.2,0.7,2.4,15.4,37.2,Y
997,669,87654,M,30,7.1,81,6.7,4.1,1.1,1.2,2.4,8.1,27.4,Y
998,99,24004,M,38,5.8,59,6.7,5.3,2.0,1.6,2.9,14.0,40.5,Y
999,248,24054,M,54,5.0,67,6.9,3.8,1.7,1.1,3.0,0.7,33.0,Y

In [49]:
df["Urea"].max()

38.9

In [53]:
df["Urea_percentage"]=df["Urea"]*100/38.9

In [54]:
df["Urea_percentage"]

0      12.082262
1      11.568123
2      12.082262
3      12.082262
4      18.251928
         ...
995    28.277635
996     7.712082
997    18.251928
998    14.910026
999    12.853470
Name: Urea_percentage, Length: 1000, dtype: float64

In [55]:
df["Urea_percentage"].max()

100.0

In [56]:
df.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Urea_percentage
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020,13.174147
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388,7.545412
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000,1.285347
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000,9.511568
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000,11.825193
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000,14.652956
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000,100.000000